stages:
  - build
  - test
  - package
  - docker
  - deploy

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script: "mvn compile"

maven-test:
  image: maven:3-openjdk-11
  stage: test
  script: "mvn test"

maven-package:
  image: maven:3-openjdk-11
  stage: package
  script: "mvn clean package"
  artifacts:
    paths:
      - target/IT-Hackathon-0.0.1-SNAPSHOT.jar

docker-build:
  stage: docker
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_HUB_USER: $DOCKER_HUB_USER
    DOCKER_HUB_PASSWORD: $DOCKER_HUB_PASSWORD
    DOCKER_HUB_URL: $DOCKER_HUB_URL
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD $DOCKER_HUB_URL
    - docker build --tag eren51/it-hackathon:latest .
    - docker push eren51/it-hackathon:latest

minikube-deploy:
  stage: deploy
  image:
     name: bitnami/kubectl:latest
     entrypoint: [""]
  script:
   - kubectl config get-contexts
   - kubectl config use-context erendogan1/it-hackathon:minikube
   - kubectl apply -f deployment.yml
   - kubectl get pods
